{include file='header.tpl'}
			<div id = "content">
				<div class="sadrzaj">
					<h4>Opis projektnog rješenja</h4> 
				</div>
				<div class="sadrzaj_glavni">
<p align="center"><h3 align="center">Praćenje troškova evidencija primitaka/izdataka na razini osobe/kućanstva</h3></p><br>
Sustav omogućuje praćenje kretanja troškova unutar oragnizirane zajednice (npr. kućanstvo) u definiranom intervalu (od – do, za određeni mjesec, na razini tjedna i sl.) od strane članova organizirane zajednice. Sustav ima sljedeće korisnike:
	<ul>
    <li><b>Neregistrirani korisnik</b> je korisnik koji nema korisnički račun na sustavu. Članom sustava može postati u slučaju registracije na sustav, bilo putem OpenID računa (Google, Facebook i druge sustavi koji podržavaju OID) ili putem ugradenog sustava za registraciju korisnika. Korisnik se smatra registriranim tek nakon aktivacije račune putem aktivacijse poruke elektroničke pošte (link za aktivaciju vrijedi 24 sati). Neregistrirani korisnik ima pravo uvida u mjesečno praćenje troškova nasumično odabrane organizirane zajednice nakon prethodne anonimizacije tih podataka. Isto tako ima pravo uvida u prosječne troškove na razini svih zajednica kao i na razini prosječnog korisnika.</li>
    <li><b>Registrirani korisnik</b> ima kreiran i aktiviran korisnički račun. U slučaju tri neuspješne prijave na sustav (za redom), korisniku se zaključava pristup sustavu; u tom slučaju se aktiviranje korisničkog računa obavlja od strane administratora sustava. U slučaju uspješne prijave na sustav, kreira se korisnička sesija koja traje ili do isteka vremena podešenog od strane servera (default: 30 minuta) ili do odjave korisnika sa sustava. Registrirani korisnik ima sva prava kao i neregistrirani korisnik. Ima prava uvida u prosječne troškove odredene zajednice bez informacije o članovima zajednice kao niti o vrsti troškova koje to zajednica ima. Svaki registrirani korisnik je član zajednice. Članove zajednice odobravaju moderatori zajednice nakon što korisnik pošalje zahtjev za prihvaćanje u zajednicu. Nakon primanja u zajednicu svaki član zajednice ima pravo kreiranja novog tipa troška i unošenja iznosa troškova koje je ostvario. Osim toga, ima pravo komentiranja troškove drugih korisnika iste zajednice kako i ocjenjivanje njihovih troškova. Svaki korisnik mora pripadati barem jednoj zajednici ali može pripadati više njih. On može, takoder, pretraživati (unutar troškova i korisnika zajednice) članove po imenu, po najvećoj/najmanjoj prosječnoj ocjeni, praćenje kretanja odredenog troška po svim ukućanima kroz grafički prikaz (npr. plaćanje telefonskog računa; za ovu opciju mora postojati barem n upisa tog troška u sustav za tu zajedincu; n se definira putem konfiguracijske skripte za što je zadužen voditelj zajednice), vidjet kronološki ispis postojećih troškova (prema potrebi, sa straničenjem), vidjeti ispis troškova jednog korisnika (prema potrebi, sa straničenjem), usporedba svojih troškova sa odabranim članom zajednice (u odabranom razdoblju, sa grafičkim prikazom). Kod upisa troškova korisnik ima opciju kreiranja novog troška ili odabira već prije kreiranog troška. Datum ostvarenog troška je trenutni virtulani datum. Unos iznosa je prema formatu xxx.xxx,xx. Svaki korisnik može kreirati set predložaka koje koristi prema potrebi. Svaki unos troška se stavlja u košaricu i prije upisa u evidenciju se korisniku nudi mogućnost kontrole unešenih troškova. Svakom korisniku se omogućuje unos skeniranog računa kao priloga unešenom trošku. Unos korisničkih dokumenta u sustav je ograničen na formate jpg, jpeg te png. Iz unešenih dokumenata se kreira galerija slika zajedno sa podacima o trošku.</li>
    <li><b>Voditelj zajednice</b> ima sve ovlasti i mogućnosti kao i registrirani korisnik uz mogućnosti upravljanja zajednicom. Voditelj zajednice se postaje kreiranjem zajednice i pozivanjem ljudi u zajednicu, ukoliko se oni nalaze u sustavu. Ukoliko se ne nalaze u sustva prilikom kreiranja zajednice, članovi se dodaju na njihov zahtjev nakon uspješne registracije. Osim dodavanja članova, ovaj tip korisnika ima pravo odbijanja/brisanja iz članstva, zamrzavanja pristupa zajednici na X dana odredenom korisniku, praćenje aktivnosti korisnika, praćenje medusobnih komentara, kreiranje analize rada sustava, praćenja troškova po tipu, iznosu, datumu, vremenskom intervalu i slično.</li>
    <li><b>Administrator sustava</b> ma sva prava kao i voditelj zajednice uz ovlasti upravljanja korisničkim podacima svakog korisnika, uvida u statistiku rada sustava, uvid u statistiku pojedinog korisnika, uvid u statistiku pojedine zajednice, odobravanje/brisanje zajednice, članstva u zajednici, blokiranja korisničkih računa u slučaju povrede pravila korištenja (pritužba drugih korisnika, pritužba voditelja zajednice, vulgarni komentari i tome slično), zamrzavanje korištenja računa na odredeno vrijeme (X sati, X dana,...), brisanje korisničkih računa u slučaju treće opomene, odobravanje/brisanje moderatora. Osim toga, on ima mogućnost upravljanja "sustavskim vremeno</p></li></ul>
				</div>
				
			</div>
{include file='footer.tpl'}